In [3]:
import tensorflow as tf
import numpy as np

### Indexes

In [4]:
a = [1, 2, 3, 4, 5]

In [5]:
a[2]

3

In [6]:
dd = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

In [7]:
dd[1][2]

6

### Rank
##### The rank of a tensor tells us how many axes a tensor has

In [8]:
dd = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

In [9]:
dd[0]

[1, 2, 3]

In [10]:
dd[1]

[4, 5, 6]

In [11]:
dd[2]

[7, 8, 9]

In [12]:
dd[0][2]

3

In [13]:
dd[2][1]

8

In [14]:
dd[1][0]

4

### Shape of a Tensor

In [15]:
dd = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]     #dd is a 2-D array

In [16]:
# First we will create a tensor object
t = tf.constant(dd)      # constant() creates a constant tensor
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [17]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [18]:
t.shape

TensorShape([3, 3])

### Reshaping a tensor

In [32]:
t = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ], dtype = tf.float32)

In [22]:
reshaped_tensor = tf.reshape(t, [1, 12])
print(reshaped_tensor)

tf.Tensor([[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]], shape=(1, 12), dtype=float32)


In [24]:
reshaped_tensor = tf.reshape(t, [2, 6])
print(reshaped_tensor)

tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]], shape=(2, 6), dtype=float32)


In [25]:
reshaped_tensor = tf.reshape(t, [3, 4])
print(reshaped_tensor)

tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]], shape=(3, 4), dtype=float32)


In [26]:
reshaped_tensor = tf.reshape(t, [2, 2, 3])
print(reshaped_tensor)

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


In [37]:
reshaped_tensor = tf.reshape(t, [2, -1])
reshaped_tensor

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)>

### Squeezing and Unsqueezing a tensor

In [27]:
print(tf.reshape(t, [1, 12]))

tf.Tensor([[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]], shape=(1, 12), dtype=float32)


In [28]:
print(tf.reshape(t, [1, 12]).shape)

(1, 12)


In [29]:
print(tf.squeeze(tf.reshape(t, [1, 12])))

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.], shape=(12,), dtype=float32)


In [31]:
print(tf.squeeze(tf.reshape(t, [1, 12])).shape)

(12,)


### Flatten a Tensor
##### squeezing a tensor by building a flatten function.

In [43]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    return t

In [44]:
t = tf.ones([4, 3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [45]:
flatten(t)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

### Concatenating Tensors

In [46]:
t1 = tf.constant([
    [1, 2],
    [3, 4]
    ])
t2 = tf.constant([
    [5, 6],
    [7, 8]
    ])

In [49]:
tf.concat((t1, t2), axis = 0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [52]:
tf.concat((t1, t2), axis = 0).shape

TensorShape([4, 2])

In [50]:
tf.concat((t1, t2), axis = 1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])>

In [53]:
tf.concat((t1, t2), axis = 1).shape

TensorShape([2, 4])

### Ranked Tensor

In [55]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [56]:
rank_1_tensor = tf.constant([1, 3, 4, 6, 7])
print(rank_1_tensor)

tf.Tensor([1 3 4 6 7], shape=(5,), dtype=int32)


In [57]:
rank_2_tensor = tf.constant([[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [58]:
rank_3_tensor = tf.constant([[[1, 2, 3, 4, 5],
                              [6, 7, 8, 9, 10]],
                             [[11, 12, 13, 14, 15],
                              [16, 17, 18, 19, 20]],
                             [[21, 22, 23, 24, 25],
                              [26, 27, 28, 29, 30]]])
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]], shape=(3, 2, 5), dtype=int32)


### Tensor to Numpy array

In [60]:
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
rank_2_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Maths on Tensors

In [62]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[4, 3],
                 [2, 1]])

print(tf.add(a, b), '\n')
print(tf.multiply(a, b), '\n')
print(tf.matmul(a, b), '\n')

tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[4 6]
 [6 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 8  5]
 [20 13]], shape=(2, 2), dtype=int32) 



In [63]:
print((a + b), '\n')             # elementwise addition
print((a * b), '\n')             # elementwise multiplication
print((a @ b), '\n')             # matrix multiplication

tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[4 6]
 [6 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 8  5]
 [20 13]], shape=(2, 2), dtype=int32) 



In [67]:
rank_4_tensor = tf.ones([3, 2, 2, 4])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 2, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [71]:
print('Type of every element:', rank_4_tensor.dtype, '\n')
print('Number of Dimensions:', rank_4_tensor.ndim, '\n')
print('Shape of Tensor:', rank_4_tensor.shape, '\n')
print('Elements along axis 0 of Tensor:', rank_4_tensor.shape[0], '\n')
print('Elements along last axis of Tensor:', rank_4_tensor.shape[-1], '\n')
print('Size of Tensor:', tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'> 

Number of Dimensions: 4 

Shape of Tensor: (3, 2, 2, 4) 

Elements along axis 0 of Tensor: 3 

Elements along last axis of Tensor: 4 

Size of Tensor: 48


### Indexing

#### Single axis indexing

In [72]:
rank_1_tensor = tf.constant([2, 4, 6, 7, 23, 87, 21, 98])
print(rank_1_tensor.numpy())

[ 2  4  6  7 23 87 21 98]


In [75]:
print('First:', rank_1_tensor[0].numpy(), '\n')
print('Second:', rank_1_tensor[1].numpy(), '\n')
print('Last:', rank_1_tensor[-1].numpy(), '\n')

First: 2 

Second: 4 

Last: 98 



In [76]:
print('Everything:', rank_1_tensor[:].numpy(), '\n')
print('Before 4:', rank_1_tensor[:4].numpy(), '\n')
print('From 4 to the end:', rank_1_tensor[4:].numpy(), '\n')
print('From 2, before 7:', rank_1_tensor[2:7].numpy(), '\n')
print('Every other item:', rank_1_tensor[::2].numpy(), '\n')
print('Reversed:', rank_1_tensor[::-1].numpy(), '\n')

Everything: [ 2  4  6  7 23 87 21 98] 

Before 4: [2 4 6 7] 

From 4 to the end: [23 87 21 98] 

From 2, before 7: [ 6  7 23 87 21] 

Every other item: [ 2  6 23 21] 

Reversed: [98 21 87 23  7  6  4  2] 



#### Multi-axis indexing

In [77]:
print(rank_2_tensor.numpy())

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(rank_2_tensor[1, 1].numpy())

5


In [79]:
print('Second row:', rank_2_tensor[1, :].numpy())
print('Second column:', rank_2_tensor[:, 1].numpy())
print('Last row:', rank_2_tensor[-1, :].numpy())
print('First item in last column:', rank_2_tensor[0, -1].numpy())
print('Skip the first row:', rank_2_tensor[1: ,:].numpy())

Second row: [4 5 6]
Second column: [2 5 8]
Last row: [7 8 9]
First item in last column: 3
Skip the first row: [[4 5 6]
 [7 8 9]]


In [80]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 5 10]
 [15 20]
 [25 30]], shape=(3, 2), dtype=int32)


### Manipulating shapes

In [110]:
# Variables
# Most tensor operations work on variables as expected, although variables cannot be reshaped.
# A tf.Variable represents a tensor whose value can be changed by running ops on it. 
# Specific ops allow you to read and modify the values of this tensor. Not possible on a normal tensor
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [111]:
var_x = tf.Variable(tf.constant([[3, 3], 
                                 [4, 4], 
                                 [7, 7], 
                                 [12, 12]]))
print(var_x.shape)                   # shape returns a `TensorShape` object that shows the size on each dimension

(4, 2)


In [112]:
print(var_x.shape.as_list())

[4, 2]


In [113]:
reshaped = tf.reshape(var_x, [1, 4])
reshaped

InvalidArgumentError: Input to reshape is a tensor with 8 values, but the requested shape has 4 [Op:Reshape]

In [114]:
print(var_x.shape)
print(reshaped.shape)

(4, 2)
(1, 4)


In [115]:
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]], shape=(3, 2, 5), dtype=int32)


In [116]:
print(tf.reshape(rank_3_tensor, [1, -1]))
print(tf.reshape(rank_3_tensor, [-1]))         # -1 passed in the `shape` argument says "Whatever fits"

tf.Tensor(
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]], shape=(1, 30), dtype=int32)
tf.Tensor(
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30], shape=(30,), dtype=int32)


In [117]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), '\n')
print(tf.reshape(rank_3_tensor, [3, -1]), '\n')

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]], shape=(3, 10), dtype=int32) 



### Dtypes

In [118]:
float64_tensor = tf.constant([2.3, 5.8, 9.4], dtype = tf.float64)
print(float64_tensor)
float16_tensor = tf.cast(float64_tensor, dtype = tf.float16)
print(float16_tensor)
uint8_tensor = tf.cast(float16_tensor, dtype = tf.uint8)
print(uint8_tensor)

tf.Tensor([2.3 5.8 9.4], shape=(3,), dtype=float64)
tf.Tensor([2.3 5.8 9.4], shape=(3,), dtype=float16)
tf.Tensor([2 5 9], shape=(3,), dtype=uint8)


### Convert to tensor

In [119]:
dd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [120]:
tf.convert_to_tensor(dd)  
# Most object classes like NumPy's ndarray, TensorShape, Python lists and tf.Variable will all get converted to Tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>